<Project>
  <Import Project="packages\Microsoft.Windows.WDK.x64.10.0.28000.2526\build\native\Microsoft.Windows.WDK.x64.props"
          Condition="'$(MSBuildProjectExtension)' == '.vcxproj' and '$(Platform)' == 'x64' and Exists('packages\Microsoft.Windows.WDK.x64.10.0.28000.2526\build\native\Microsoft.Windows.WDK.x64.props')" />
  <Import Project="packages\Microsoft.Windows.SDK.CPP.x64.10.0.28000.2526\build\native\Microsoft.Windows.SDK.cpp.x64.props"
          Condition="'$(MSBuildProjectExtension)' == '.vcxproj' and '$(Platform)' == 'x64' and Exists('packages\Microsoft.Windows.SDK.CPP.x64.10.0.28000.2526\build\native\Microsoft.Windows.SDK.cpp.x64.props')" />
  <Import Project="packages\Microsoft.Windows.SDK.CPP.10.0.28000.2526\build\native\Microsoft.Windows.SDK.cpp.props"
          Condition="'$(MSBuildProjectExtension)' == '.vcxproj' and Exists('packages\Microsoft.Windows.SDK.CPP.10.0.28000.2526\build\native\Microsoft.Windows.SDK.cpp.props')" />

  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    <Version>1.0.0-rc.1</Version>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
    <FileVersion>1.0.0.0</FileVersion>
    <Company>ROOOMTECH株式会社</Company>
    <Product>ROOOMTECH AI Guard</Product>
    <Copyright>Copyright © 2026 ROOOMTECH株式会社</Copyright>
  </PropertyGroup>
</Project>
