<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <AssemblyName>AIGuard.Desktop</AssemblyName>
    <RootNamespace>Rooomtech.AIGuard.Desktop</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\AI.Guard.Core\AI.Guard.Core.csproj" />
  </ItemGroup>
</Project>
